---
- name: Установка и настройка Nginx на Ubuntu через jump host
  hosts: webservers
  become: yes
  become_user: root

  vars:
    nginx_config_path: /etc/nginx/nginx.conf
    web_root: /var/www/html

  pre_tasks:
    - name: Проверка, установлен ли Nginx
      ansible.builtin.command: dpkg -l nginx
      ignore_errors: yes
      changed_when: false
      register: nginx_installed

    - name: Вывод статуса установки Nginx
      ansible.builtin.debug:
        msg: "✅ Nginx уже установлен на {{ ansible_hostname }}"
      when: nginx_installed.rc == 0

    - name: Nginx будет установлен
      ansible.builtin.debug:
        msg: "🔧 Nginx ещё не установлен. Начинаем установку..."
      when: nginx_installed.rc != 0

    - name: Убедиться, что /var/www/html существует
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

  tasks:
    - name: Установка Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Копирование кастомного nginx.conf
      ansible.builtin.copy:
        src: ./nginx.conf
        dest: "{{ nginx_config_path }}"
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: Проверить конфиг и перезагрузить Nginx

    - name: Размещение кастомной страницы my.html
      ansible.builtin.template:
        src: templates/my.html.j2
        dest: "{{ web_root }}/my.html"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Удалить стандартный сайт Nginx, (конфликт default_server)
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Запуск и включение Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Проверить конфиг и перезагрузить Nginx
      ansible.builtin.shell: |
        if nginx -t; then
          systemctl reload nginx
          echo "✅ Nginx: конфиг валиден, перезагружен."
        else
          echo "❌ Ошибка: конфигурация Nginx невалидна!"
          exit 1
        fi
      args:
        executable: /bin/bash