services:
  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: paninang-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - paninang-netology-hw
    restart: always
volumes:
  prometheus-data:
networks:
  paninang-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16