version: '3.3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  filatovvk-my-netology-hw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: filatovvk-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - filatovvk-my-netology-hw
    restart: always

  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: filatovvk-pushgateway
    ports:
      - 9091:9091
    networks:
      - filatovvk-my-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: filatovvk-grafana
    env_file:
    - ./grafana/config.monitoring
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - filatovvk-my-netology-hw
    depends_on:
      - pushgateway
      - prometheus
    restart: unless-stopped
