input {
  tcp {
    port => 5000
    codec => json
    type => "dummy_json"
  }
  beats {
    port => 5044
    type => "filebeat"
  }
}

filter {}

output {
  if [type] == "dummy_json" {
    elasticsearch {
      hosts => ["http://es-hot:9200"]
      index => "logstash-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://es-hot:9200"]
      index => "filebeat-%{+YYYY.MM.dd}"
    }
  }
}