[tox]
envlist = molecule
skipsdist = true

[testenv]
deps = -r tox-requirements.txt
setenv =
    ALLOW_BROKEN_CONDITIONALS = 1
    ANSIBLE_LINT_ENABLED = false
    ANSIBLE_LINT_SKIP = role-name,name[casing],schema
commands =
    molecule test -s tox --driver-name podman