---
# Внешняя роль ClickHouse
- name: clickhouse-role
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"

# Кастомные роли
  src: git@github.com:LuckyVl/vector-role.git
  scm: git
  version: "v1.0.0"

- name: lighthouse-role
  src: git@github.com:LuckyVl/lighthouse-role.git
  scm: git
  version: "v1.0.0"